import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createStaticServer} from '../../scripts/serve.mjs';
import {installAuthFixture} from './fixtures/auth.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const server=await createStaticServer({port:0}),browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})}),url=`http://127.0.0.1:${server.address().port}/`;
const output='output/nhpl-entrega-2026-10-07/visual';await mkdir(output,{recursive:true});const errors=[],results=[];
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',err=>errors.push(err.message));await installAuthFixture(page,{role:'admin'});await page.goto(url);
 await page.locator('#login [name=re]').fill('00000');await page.locator('#login [name=password]').fill('fixture-only');await page.locator('#login [type=submit]').click();await page.locator('.zones .zone').first().waitFor();
 await page.locator('.rail a[href="#registry"]').click();await page.locator('[data-action="nhpl:install"]').click();await page.locator('#modal [name=confirmed]').check();await page.locator('#modal [type=submit]').click();await page.waitForFunction(()=>!document.getElementById('modal').open);
 await page.locator('.rail a[href="#planning"]').click();
 const close=async()=>{await page.locator('#modal [type=submit]').click();await page.waitForFunction(()=>!document.getElementById('modal').open);};
 for(const [metric,value] of [['productivityPercent','95'],['taktSeconds','12']]){await page.locator('[data-action="nhpl:policy"]').click();await page.locator('#modal [name=metric]').selectOption(metric);await page.locator('#modal [name=value]').fill(value);await page.locator('#modal [name=effectiveFrom]').fill('2026-10-07T00:00');await close();}
 await page.locator('[data-action="nhpl:plan"]').click();
 for(const [field,value] of Object.entries({order:'OP-TESTE',lot:'L-TESTE',shift:'1',startedAt:'2026-10-07T08:00',endedAt:'2026-10-07T09:00'}))await page.locator(`#modal [name=${field}]`).fill(value);
 await page.locator('#modal [name=quantitySource]').selectOption('takt');await page.locator('#modal [type=submit]').click();await page.locator('#plan-preview [name=confirmed]').check();assert.match(await page.locator('#plan-preview').innerText(),/300/);await close();
 await page.locator('.rail .rail-link[href="#dashboard"]').click();await page.locator('[data-action^="nhpl:production:"]').first().click();await page.locator('#modal [name=quantity]').fill('285');await close();
 await page.locator('[data-action^="nhpl:confirm:"]').first().click();assert.equal(await page.locator('#modal [name=quantity]').inputValue(),'285');await page.locator('#modal [name=confirmed]').check();await close();assert.match(await page.locator('#page').innerText(),/95%/);
 const download=page.waitForEvent('download');await page.locator('[data-action="nhpl:export"]').click();const file=await download;await file.saveAs('output/nhpl-entrega-2026-10-07/productivity.csv');const csv=await readFile('output/nhpl-entrega-2026-10-07/productivity.csv','utf8');assert.match(csv,/OP-TESTE/);assert.match(csv,/gross/);assert.doesNotMatch(csv,/\[object Promise\]/);
 await page.locator('.rail a[href="#planning"]').click();await page.locator('[data-action="nhpl:run"]').click();await page.locator('#modal [name=at]').fill('2026-10-07T07:30');await close();
 for(const time of ['08:00','09:00','09:30']){await page.locator('[data-action^="nhpl:advance-run:"]').click();await page.locator('#modal [name=at]').fill('2026-10-07T'+time);await close();}assert.equal(await page.locator('[data-action^="nhpl:advance-run:"]').count(),0);assert.match(await page.locator('#page .nhpl-panel').last().innerText(),/285 peças/);await page.waitForFunction(()=>!document.getElementById('toast').classList.contains('show'));await page.screenshot({path:`${output}/planning-1440-light.png`,fullPage:true});
 for(const [width,height] of [[1440,900],[768,1024],[390,844]]){await page.setViewportSize({width,height});await page.goto(url+'#dashboard');await page.locator('.rail').waitFor();if(width<=600){await page.waitForFunction(()=>document.querySelector('.rail').getBoundingClientRect().right<=0);await page.locator('[data-action=menu]').click();await page.waitForFunction(()=>document.querySelector('.rail').classList.contains('open')&&document.querySelector('.rail').getBoundingClientRect().left>=0);await page.locator('[data-action=menu-close]').click({position:{x:200,y:100}});await page.waitForFunction(()=>document.querySelector('.rail').getBoundingClientRect().right<=0);await page.locator('[data-action=menu]').click();await page.waitForFunction(()=>document.querySelector('.rail').classList.contains('open'));await page.keyboard.press('Escape');await page.waitForFunction(()=>document.querySelector('.rail').getBoundingClientRect().right<=0);}await page.evaluate(()=>document.activeElement?.blur());await page.screenshot({path:`${output}/nhpl-${width}-light.png`,fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));results.push({width,height,overflow:false});}
 await page.goto(url+'#settings');await page.locator('[data-theme-choice=dark]').click();await page.goto(url+'#dashboard');await page.screenshot({path:`${output}/nhpl-390-dark.png`,fullPage:true});await page.close();
 for(const role of ['engineer','operator','viewer']){
  const p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',err=>errors.push(err.message));await installAuthFixture(p,{role});await p.goto(url);await p.locator('#login [name=re]').fill(role==='engineer'?'00001':role==='operator'?'00002':'00003');await p.locator('#login [name=password]').fill('fixture-only');await p.locator('#login [type=submit]').click();await p.locator('.rail').waitFor();
  if(role!=='engineer'){assert.equal(await p.locator('.rail a[href="#registry"]').count(),0);assert.equal(await p.locator('.rail a[href="#engineering"]').count(),0);}
  await p.goto(url+'#dashboard');await p.locator('[data-action=simulate]').click();await p.locator('#modal [name=scenario]').selectOption('nhpl-met');await p.locator('#modal [type=submit]').click();await p.locator('.simulation-notice').waitFor();assert.match(await p.locator('#page').innerText(),/95%/);
  await p.goto(url+'#planning');assert.equal(await p.locator('[data-action="nhpl:plan"]').count(),role==='engineer'?1:0);assert.equal(await p.locator('[data-action="nhpl:run"]').count(),role==='viewer'?0:1);
  await p.locator('[data-action=end-simulation]').click();await p.waitForFunction(()=>!document.querySelector('.simulation-notice'));results.push({role,simulationRolePreserved:true});await p.close();
 }
 assert.deepEqual(errors,[]);await writeFile('output/nhpl-entrega-2026-10-07/browser.json',JSON.stringify({fixtureOnly:true,results,errors},null,2));console.log('NHPL: install, policies, approved plan, production, confirmation, CSV, four timestamps, role-bound simulations and 3 viewports passed.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
