import {assertShiftPeriod} from '../domain/shifts.js';
import {assertRole,assertId,requireThat} from '../domain/errors.js';
import {loadContext} from '../domain/context.js';
import {suggestPlan,latestPlans,conflictingPlans} from '../domain/planning.js';
import {initLedger,readLedger,appendLedgerEvent} from '../repositories/append-ledger.js';
import {eventDate} from '../domain/time.js';
export function createPlanningService({repo,actor,enforceOperationalShifts=false,idFactory=()=>crypto.randomUUID()}){
 const options={actor,idFactory};
 async function retire(plan){
  const intervals=[];for(const interval of plan.intervals){const view=await readLedger(repo,'productionIntervals/'+interval.id);requireThat(view.complete,'INCOMPLETE_DATA');requireThat(!view.events.some(e=>['production','closure'].includes(e.kind)),'CORRECTION_REQUIRED');intervals.push({interval,view});}
  for(const {interval,view} of intervals)if(view.last?.kind!=='retire')await appendLedgerEvent(repo,'productionIntervals/'+interval.id,{expectedEventId:view.last?.id??null,event:{kind:'retire',planRevisionId:plan.id,createdBy:actor.uid,createdAt:repo.timestamp()}},options);
 }
 async function write(payload,previous){assertRole(actor,['admin','engineer']);const context=await loadContext(repo,payload.context);if(enforceOperationalShifts)assertShiftPeriod(context,payload.startedAt,payload.endedAt);const draft=suggestPlan({...payload,context});const path='productionPlans/'+context.machineId;await initLedger(repo,path,{machineId:context.machineId},options);const view=await readLedger(repo,path);requireThat(view.complete,'INCOMPLETE_DATA');
  const plans=latestPlans(view.events),old=previous?plans.find(p=>p.planId===previous):null;if(previous)requireThat(old&&payload.reason?.trim(),'JUSTIFICATION_REQUIRED');
  requireThat(!conflictingPlans([...plans.filter(p=>p.planId!==previous),{...draft,planId:previous??'new'}]).length,'PLAN_OVERLAP');
  if(old)await retire(old);
  const planId=previous??assertId(idFactory()),intervals=draft.intervals.map(r=>({...r,id:assertId(idFactory())}));const revision=await appendLedgerEvent(repo,path,{expectedEventId:payload.expectedResourceRevision??view.last?.id??null,event:{...draft,intervals,planId,kind:'plan',eventDate:eventDate(draft.startedAt),createdBy:actor.uid,createdAt:repo.timestamp(),...(old?{supersedes:old.id,reason:payload.reason}:{})}},options);
  for(const [index,interval] of intervals.entries())await initLedger(repo,'productionIntervals/'+interval.id,{context,planId,planRevisionId:revision.id,intervalIndex:String(index),startedAt:interval.startedAt,endedAt:interval.endedAt,eventDate:eventDate(interval.startedAt),plannedPieces:interval.plannedPieces},options);return revision;
 }
 return {suggest:payload=>suggestPlan(payload),approve:payload=>write(payload),async restore(machineId,planId){assertRole(actor,['admin','engineer']);const resource=await readLedger(repo,'productionPlans/'+assertId(machineId)),plan=latestPlans(resource.events).find(p=>p.planId===planId);requireThat(resource.complete&&plan,'NOT_FOUND');for(const interval of plan.intervals){const view=await readLedger(repo,'productionIntervals/'+interval.id);requireThat(view.complete&&view.header.planRevisionId===plan.id,'STALE_PLAN');if(view.last?.kind==='retire')await appendLedgerEvent(repo,'productionIntervals/'+interval.id,{expectedEventId:view.last.id,event:{kind:'restore',planRevisionId:plan.id,createdBy:actor.uid,createdAt:repo.timestamp()}},options);}return plan;},async reconcile(machineId,planId){assertRole(actor,['admin','engineer']);const view=await readLedger(repo,'productionPlans/'+assertId(machineId));requireThat(view.complete,'INCOMPLETE_DATA');const plan=latestPlans(view.events).find(p=>p.planId===planId);requireThat(plan,'NOT_FOUND');for(const [intervalIndex,interval] of plan.intervals.entries())await initLedger(repo,'productionIntervals/'+interval.id,{context:plan.context,planId,planRevisionId:plan.id,intervalIndex:String(intervalIndex),startedAt:interval.startedAt,endedAt:interval.endedAt,eventDate:eventDate(interval.startedAt),plannedPieces:interval.plannedPieces},options);return plan;},async revise(planId,payload){const view=await readLedger(repo,'productionPlans/'+assertId(payload.machineId));const previous=latestPlans(view.events).find(r=>r.planId===planId);requireThat(previous,'NOT_FOUND');return write({...previous,...payload,context:payload.context??previous.context},planId);}};
}
