import {assertRole,assertId,requireThat,knownKeys} from '../domain/errors.js';
import {validatePolicy} from '../domain/production-policy.js';
import {initLedger,readLedger,appendLedgerEvent} from '../repositories/append-ledger.js';
import {eventDate,validateDate} from '../domain/time.js';
export function createProductionPolicyService({repo,actor,idFactory=()=>crypto.randomUUID()}) {
 const options={actor,idFactory};
 async function create(payload){assertRole(actor,['admin','engineer']);knownKeys(payload,['id','metric','value','effectiveFrom','effectiveTo','source','context']);validatePolicy(payload);const id=assertId(payload.id??idFactory()),path='productionPolicies/'+id;requireThat(!await repo.get(path),'CONFLICT');await initLedger(repo,path,{metric:payload.metric,context:payload.context},options);return appendLedgerEvent(repo,path,{expectedEventId:null,event:{...payload,id:undefined,policyId:id,kind:'policy',eventDate:eventDate(payload.effectiveFrom),createdBy:actor.uid,createdAt:repo.timestamp()}},options);}
 return {create,async revise(id,payload){assertRole(actor,['admin','engineer']);knownKeys(payload,['expectedRevisionId','value','effectiveFrom','effectiveTo','source','reason']);const path='productionPolicies/'+assertId(id),view=await readLedger(repo,path);requireThat(typeof payload.reason==='string'&&payload.reason.trim().length>0,'JUSTIFICATION_REQUIRED');const value={metric:view.header.metric,context:view.header.context,value:payload.value,effectiveFrom:payload.effectiveFrom,source:payload.source,...(payload.effectiveTo!=null?{effectiveTo:payload.effectiveTo}:{})};validatePolicy(value);requireThat(payload.effectiveFrom>=view.last.effectiveFrom,'REVISION_CONFLICT');return appendLedgerEvent(repo,path,{expectedEventId:payload.expectedRevisionId,event:{...value,policyId:id,kind:'policy',supersedes:payload.expectedRevisionId,reason:payload.reason,eventDate:eventDate(payload.effectiveFrom),createdBy:actor.uid,createdAt:repo.timestamp()}},options);},
 async reviseTarget(id,payload){assertRole(actor,['admin','engineer']);knownKeys(payload,['name','operator','threshold','fromDate','toDate','reason','expectedRevisionId']);const original=await repo.get('targets/'+assertId(id));requireThat(original,'NOT_FOUND');const path='targetRevisions/'+id;await initLedger(repo,path,{targetId:id},options);const view=await readLedger(repo,path);const row={...original,...payload};delete row.expectedRevisionId;requireThat(row.reason?.trim(),'JUSTIFICATION_REQUIRED');validateDate(row.fromDate);validateDate(row.toDate);requireThat(row.toDate>=row.fromDate&&Number.isFinite(row.threshold)&&row.threshold>=0&&['lower','upper'].includes(row.operator)&&typeof row.name==='string'&&row.name.trim().length>0&&row.name.length<=160,'VALIDATION');return appendLedgerEvent(repo,path,{expectedEventId:payload.expectedRevisionId??null,event:{kind:'target',targetId:id,name:row.name,metric:original.metric,unit:original.unit,operator:row.operator,threshold:row.threshold,context:row.context,fromDate:row.fromDate,toDate:row.toDate,reason:row.reason,createdBy:actor.uid,createdAt:repo.timestamp()}},options);}
 };
}
