import {projectProductivity} from '../domain/workspace-metrics.js';
import {escapeHtml as e,number as n,date,dateWindow} from './format.js';
import {saoPauloInstant} from './forms.js';
import {parseReading} from '../domain/numbers.js';
import {requireThat} from '../domain/errors.js';
import {latestPlans} from '../domain/planning.js';
import {ledgerView} from '../repositories/append-ledger.js';
import {buildProductivity} from '../domain/productivity.js';
import {matchesScope} from '../domain/production-policy.js';
const names={programmed:'Programado',partial:'Parcial',final:'Confirmado',unavailable:'Indisponível','not-scheduled':'Sem programação',inconsistent:'Inconsistente'};
const reasons={'planning-required':'Plano aprovado ausente','confirmation-required':'Confirmação pendente','production-required':'Apontamento ausente','policy-required':'Meta vigente ausente','incomplete-query':'Consulta incompleta','plan-conflict':'Planos sobrepostos','policy-conflict':'Metas conflitantes','correction-conflict':'Correções conflitantes','no-period-allocation':'Intervalo atravessa o recorte ou a vigência da meta','revision-mismatch':'Revisão divergente','confirmation-outdated':'Confirmação anterior à correção; reconciliar','confirmation-mismatch':'Total ou referências não conferem','revision-pending':'Revisão de plano interrompida','obsolete-plan':'Apontamento de revisão substituída; conciliação pendente'};
const local=value=>new Date(value-10800000).toISOString().slice(0,19);
const field=(label,name,value='',type='text',required=true)=>`<label class="field">${e(label)}<input name="${e(name)}" type="${type}" ${type==='datetime-local'?'step="1"':''} value="${e(value)}" ${required?'required':''} maxlength="100"></label>`;
const btn=(label,action,ico='plus')=>`<button class="btn" data-action="${e(action)}"><i data-lucide="${ico}" aria-hidden="true"></i>${e(label)}</button>`;
const can=(state,roles)=>state.client&&(state.dataset!=='presentation'||state.simulation)&&roles.includes(state.actor?.role);
const engineering=state=>can(state,['admin','engineer']),operator=state=>can(state,['admin','engineer','operator']);
const num=(data,key)=>{const r=parseReading(data.get(key));requireThat(r.status==='valid','INVALID_QUANTITY',key);return r.value;};
export const productivityView=projectProductivity;
export function productivityMarkup(state,{compact=false,actions=true}={}){
 const view=productivityView(state),aggregate=view.aggregate;
 return `<section class="data-section nhpl-panel"><div class="section-heading"><div><h2>Produtividade · NHPL</h2><p>Produção bruta / plano aprovado · metas e takt conforme a vigência</p></div>${state.client&&!compact?btn('CSV','nhpl:export','download'):''}</div><div class="metrics"><div class="metric"><div class="metric-title">Produtividade</div><div class="metric-value">${aggregate?n(aggregate.percent)+'%':'Indisponível'}</div><p>${aggregate?`${names[aggregate.state]} · ${n(aggregate.grossPieces)} / ${n(aggregate.expectedPieces)} peças · cobertura ${n(aggregate.coverage*100)}%`:'Sem resultado confirmado no período'}</p></div><div class="metric"><div class="metric-title">Meta aplicada</div><div class="metric-value">${aggregate?n(aggregate.targetPercent)+'%':'Por intervalo'}</div><p>${aggregate?`${n(aggregate.minimumPieces)} peças mínimas`:'Confira as vigências no planejamento'}</p></div></div>${compact?'':segmentTable(actions?state:{...state,client:null},view)}</section>`;
}
function segmentTable(state,view){const edit=operator(state);return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Intervalo / OP</th><th>Plano / bruta</th><th>Produtividade / meta</th><th>Situação</th>${edit?'<th>Ações</th>':''}</tr></thead><tbody>${view.segments.map(s=>`<tr><td>${s.from?date(s.from,true)+' – '+date(s.to,true):'Sem plano'}<div class="small muted">${e(s.context?.order??'')} · ${e(s.context?.lot??'')} · turno ${e(s.context?.shift??'')}</div></td><td>${n(s.plannedPieces)} / ${n(s.grossPieces)}<div class="small muted">Boas: ${n(s.goodPieces)} · refugo: ${n(s.rejectedPieces)}</div></td><td>${s.percent==null?'Indisponível':n(s.percent)+'%'} / ${n(s.targetPercent)}%<div class="small muted">Mínimo: ${n(s.minimumPieces)} · faltam: ${n(s.remainingPieces)}</div></td><td>${e(names[s.state])}<div class="small muted">${e(reasons[s.reason]??(s.evaluation==='met'?'Meta atingida':s.evaluation==='below'?'Abaixo da meta':''))}</div></td>${edit?`<td>${s.reason==='confirmation-outdated'?btn('Reconciliar','nhpl:reconcile:'+s.intervalId,'check-check'):''}${s.intervalId&&!state.period.closures?.[s.intervalId]&&!state.period.retiredIntervals?.includes(s.intervalId)?btn('Apontar','nhpl:production:'+s.intervalId,'clipboard-pen')+btn('Confirmar','nhpl:confirm:'+s.intervalId,'check'):''}</td>`:''}</tr>`).join('')}</tbody></table></div>`;}
export function planningMarkup(state){
 function windowPieces(state,run,range){
  if(run.productionStartedAt==null||run.productionEndedAt==null||run.productionStartedAt<range.from||run.productionEndedAt>range.to||state.period.nhplComplete!==true||!state.period.coverage?.production||!state.period.coverage?.corrections)return 'Indisponível';
  const rows=(state.period.effective?.production??[]).filter(r=>r.basis==='gross'&&matchesScope(run.context,r.context)&&r.startedAt<run.productionEndedAt&&r.endedAt>run.productionStartedAt);
  if(rows.some(r=>r.startedAt<run.productionStartedAt||r.endedAt>run.productionEndedAt||r.revisionConflict))return 'Indisponível';return rows.length?n(rows.reduce((sum,r)=>sum+r.quantity,0))+' peças':'Nenhum apontamento';
 }
 const plans=latestPlans(state.period.plans??[]).filter(p=>matchesScope(state.operationalQuery?.query.context??state.context,p.context)),policies=(state.period.policies??[]).filter(p=>matchesScope(p.context,state.context));
 const range=state.operationalQuery?.range??dateWindow(state.fromDate,state.toDate),runs=new Map();for(const r of state.period.runs??[])if(matchesScope(state.context,r.context)&&r.machineStartedAt<range.to&&(r.machineEndedAt==null||r.machineEndedAt>range.from))runs.set(r.runId,r);
 return `<section class="data-section nhpl-panel"><div class="section-heading"><h2>Planos aprovados</h2>${engineering(state)&&state.context.machineId==='nhpl'?btn('Novo plano','nhpl:plan','calendar-plus'):''}</div>${plans.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>OP / lote / turno</th><th>Período</th><th>Plano</th><th>Revisão</th><th>Ações</th></tr></thead><tbody>${plans.map(p=>`<tr><td>${e(p.context.order)} / ${e(p.context.lot)} / ${e(p.context.shift)}</td><td>${date(p.startedAt,true)} – ${date(p.endedAt,true)}</td><td>${n(p.plannedPieces)} peças · ${p.quantitySource==='informed'?'Informado':'Takt'} · ${p.intervalMinutes} min</td><td>${e(p.id.slice(0,8))}</td><td>${engineering(state)?btn('Revisar','nhpl:revise-plan:'+p.planId,'pencil')+btn('Conferir intervalos','nhpl:recover-plan:'+p.planId,'refresh-cw'):''}${engineering(state)&&p.intervals.some(i=>state.period.retiredIntervals?.includes(i.id))?btn('Retomar intervalos','nhpl:restore-plan:'+p.planId,'play'):''}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty-state">Sem plano aprovado</p>'}</section><section class="data-section nhpl-panel"><div class="section-heading"><h2>Metas e takt · vigências</h2>${engineering(state)&&state.context.machineId==='nhpl'?btn('Nova política','nhpl:policy','sliders-horizontal'):''}</div>${policies.map(p=>`<div class="setting-row"><div><strong>${p.metric==='taktSeconds'?'Takt':'Produtividade'}: ${n(p.value)} ${p.metric==='taktSeconds'?'s/peça':'%'}</strong><p>${date(p.effectiveFrom,true)} · ${e(p.source)} · revisão ${e(p.id.slice(0,8))}</p></div>${engineering(state)&&!policies.some(next=>next.supersedes===p.id)?btn('Revisar','nhpl:revise-policy:'+p.id,'pencil'):''}</div>`).join('')||'<p>Sem política vigente</p>'}</section><section class="data-section nhpl-panel"><div class="section-heading"><h2>Janela operacional</h2>${operator(state)&&state.context.machineId==='nhpl'?btn('Registrar máquina ligada','nhpl:run','power'):''}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>OP / lote</th><th>Máquina ligada</th><th>Produção iniciada</th><th>Produção encerrada</th><th>Máquina desligada</th><th>Produção bruta</th><th>Ações</th></tr></thead><tbody>${[...runs.values()].map(r=>`<tr><td>${e(r.context.order)} / ${e(r.context.lot)}</td>${['machineStartedAt','productionStartedAt','productionEndedAt','machineEndedAt'].map(k=>`<td>${r[k]==null?'Pendente':date(r[k],true)}</td>`).join('')}<td>${windowPieces(state,r,range)}</td><td>${operator(state)&&r.machineEndedAt==null?btn('Registrar horário','nhpl:advance-run:'+r.runId,'clock'):''}</td></tr>`).join('')||'<tr><td colspan="7">Sem janela operacional</td></tr>'}</tbody></table></div></section>`;
}
export function productivityReport(state){const view=productivityView(state);return view.segments.map(s=>({...Object.fromEntries(Object.entries(s).filter(([key])=>!['context','recordIds','correctionIds'].includes(key))),...s.context,basis:'gross',datasetOrigin:state.client?.mode==='presentation'?'presentation':state.simulation?'simulation':'operational',coverageComplete:view.coverage.complete,coverageEvaluated:view.coverage.evaluated,coverageTotal:view.coverage.total,recordIds:s.recordIds.join('|'),correctionIds:s.correctionIds.join('|')}));}
export async function nhplAction(action,{state,services,showModal,modal,refresh,downloadCsv}){
 const [,command,id]=action.split(':');
 if(command==='planning'){location.hash='planning';return;}
 if(command==='export'){const rows=productivityReport(state),columns=[...new Set(rows.flatMap(r=>Object.keys(r)))];downloadCsv(await services.csv.exportRecords(rows,columns),'msa-nhpl-'+state.toDate+'.csv');return;}
 requireThat(state.dataset!=='presentation'||state.simulation,'FORBIDDEN');
 const context=structuredClone(state.context),timestamp=data=>saoPauloInstant(data.get('at'),'at');
 if(command==='restore-plan'){requireThat(engineering(state),'FORBIDDEN');await services.planning.restore(context.machineId,id);await refresh();return;}
 if(command==='recover-plan'){requireThat(engineering(state),'FORBIDDEN');await services.planning.reconcile(context.machineId,id);await refresh();return;}
 if(command==='revise-target'){
  requireThat(engineering(state),'FORBIDDEN');const original=state.registries.targets?.[id];requireThat(original,'NOT_FOUND');const ledger=state.period.targetRevisions?.[id],chain=ledger?ledgerView(ledger):null,previous=chain?.last??original;
  showModal('Revisar meta contextual',`<p>${e(JSON.stringify(original.context))} · ${e(original.metric)} (${e(original.unit)})</p><p>Atual: ${n(previous.threshold)} · ${e(previous.fromDate)} a ${e(previous.toDate)}</p><div class="form-grid">${field('Nome','name',previous.name)}${field('Novo limite','threshold',previous.threshold)}<label class="field">Comparação<select name="operator"><option value="lower" ${previous.operator==='lower'?'selected':''}>Pelo menos</option><option value="upper" ${previous.operator==='upper'?'selected':''}>No máximo</option></select></label>${field('Data inicial','fromDate',previous.fromDate,'date')}${field('Data final','toDate',previous.toDate,'date')}${field('Motivo da revisão','reason')}</div>`,{submit:data=>services.policies.reviseTarget(id,{name:data.get('name'),threshold:num(data,'threshold'),operator:data.get('operator'),fromDate:data.get('fromDate'),toDate:data.get('toDate'),reason:data.get('reason'),expectedRevisionId:chain?.last?.id??null})});return;
 }
 if(command==='install'){
  requireThat(can(state,['admin']),'FORBIDDEN');const preview=await services.nhpl.preview();
  showModal('Cadastrar piloto NHPL',`<div class="table-wrap"><table class="data-table"><tbody>${preview.items.map(r=>`<tr><td>${e(r.payload.name)}</td><td>${e(r.status)}</td></tr>`).join('')}</tbody></table></div><label class="check-line"><input name="confirmed" type="checkbox" required>Confirmar cadastro adicional. Histórico T20/selos preservado.</label>`,{footer:'Cadastrar NHPL',submit:async data=>{requireThat(data.has('confirmed'),'CONFIRMATION_REQUIRED');const pilot=await services.nhpl.install({expectedPreview:preview});state.context={machineId:pilot.machineId,processId:pilot.processId,productId:pilot.productIds[0]};return {successMessage:'Piloto NHPL cadastrado. Nenhum limite ou leitura foi criado.'};}});return;
 }
 if(command==='policy'||command==='revise-policy'){
  requireThat(engineering(state),'FORBIDDEN');const previous=state.period.policies?.find(p=>p.id===id);
  showModal(previous?'Revisar política':'Nova política',`<div class="form-grid"><label class="field">Indicador<select name="metric" ${previous?'disabled':''}><option value="productivityPercent" ${previous?.metric==='productivityPercent'?'selected':''}>Produtividade (%)</option><option value="taktSeconds" ${previous?.metric==='taktSeconds'?'selected':''}>Takt (s/peça)</option></select></label>${field('Valor','value',previous?.value??95)}${field('Início da vigência','effectiveFrom',local(Date.now()),'datetime-local')}${field('Fonte','source',previous?.source??'Fabiana · respostas de 07/10/2026')}${previous?field('Motivo da revisão','reason'):''}</div>`,{submit:async data=>{const payload={value:num(data,'value'),effectiveFrom:saoPauloInstant(data.get('effectiveFrom'),'effectiveFrom'),source:data.get('source')};return previous?services.policies.revise(previous.policyId,{...payload,expectedRevisionId:previous.id,reason:data.get('reason')}):services.policies.create({...payload,id:crypto.randomUUID(),metric:data.get('metric'),context:{machineId:context.machineId,processId:context.processId}});}});if(!previous)modal.querySelector('[name=metric]').addEventListener('change',event=>{modal.querySelector('[name=value]').value=event.target.value==='taktSeconds'?'12':'95';});return;
 }
 if(command==='plan'||command==='revise-plan'){
  requireThat(engineering(state),'FORBIDDEN');const previous=latestPlans(state.period.plans??[]).find(p=>p.planId===id);let preview=null,payload=null;
  const ctx=previous?.context??context,start=previous?.startedAt??Date.now(),end=previous?.endedAt??start+3600000;
  showModal(previous?'Revisar plano aprovado':'Preparar plano NHPL',`<div class="form-grid">${['order','lot','shift'].map((k,i)=>field(['OP','Lote','Turno'][i],k,ctx[k])).join('')}<label class="field">Família<select name="productId" required>${Object.values(state.registries.products??{}).filter(p=>p.active&&p.processIds?.[context.processId]).map(p=>`<option value="${e(p.id)}" ${p.id===ctx.productId?'selected':''}>${e(p.name)}</option>`).join('')}</select></label><label class="field">Variante<select name="variant"><option value="">Não informada</option>${['Low','Medium','High'].map(v=>`<option ${v===ctx.variant?'selected':''}>${v}</option>`).join('')}</select></label>${field('Início','startedAt',local(start),'datetime-local')}${field('Fim','endedAt',local(end),'datetime-local')}<label class="field">Intervalo<select name="intervalMinutes">${[15,30,60].map(v=>`<option ${v===(previous?.intervalMinutes??60)?'selected':''}>${v}</option>`).join('')}</select></label><label class="field">Origem do plano<select name="quantitySource"><option value="informed">Quantidade informada</option><option value="takt" ${previous?.quantitySource==='takt'?'selected':''}>Sugestão por takt</option></select></label>${field('Quantidade informada (peças)','plannedPieces',previous?.plannedPieces??300,'text',false)}${field('Pausa planejada · início','breakStart','','datetime-local',false)}${field('Pausa planejada · fim','breakEnd','','datetime-local',false)}${previous?field('Motivo da revisão','reason'):''}</div><div id="plan-preview"></div>`,{wide:true,footer:'Conferir plano',submit:async data=>{
   if(preview){requireThat(data.has('confirmed'),'CONFIRMATION_REQUIRED');const resource=await services.planning[previous?'revise':'approve'](...(previous?[previous.planId,{...payload,machineId:context.machineId}]:[payload]));state.context=payload.context;return resource;}
   const takt=(state.period.policies??[]).filter(p=>p.metric==='taktSeconds'&&matchesScope(p.context,ctx)&&p.effectiveFrom<=saoPauloInstant(data.get('startedAt'),'startedAt')&&!state.period.policies.some(n=>n.supersedes===p.id&&n.effectiveFrom<=saoPauloInstant(data.get('startedAt'),'startedAt'))).at(-1);
   requireThat(data.get('quantitySource')==='informed'||takt,'POLICY_REQUIRED','Cadastre a vigência do takt informado de 12 s/peça.');
   const planContext={machineId:context.machineId,processId:context.processId,productId:data.get('productId'),order:data.get('order').trim(),lot:data.get('lot').trim(),shift:data.get('shift').trim(),...(data.get('variant')?{variant:data.get('variant')}:{})};
   payload={context:planContext,startedAt:saoPauloInstant(data.get('startedAt'),'startedAt'),endedAt:saoPauloInstant(data.get('endedAt'),'endedAt'),intervalMinutes:Number(data.get('intervalMinutes')),quantitySource:data.get('quantitySource'),...(data.get('quantitySource')==='informed'?{plannedPieces:num(data,'plannedPieces')}:{taktRevision:{id:takt.id,value:takt.value}}),breaks:data.get('breakStart')||data.get('breakEnd')?[{startedAt:saoPauloInstant(data.get('breakStart'),'breakStart'),endedAt:saoPauloInstant(data.get('breakEnd'),'breakEnd')}]:previous?.breaks??[],...(previous?{reason:data.get('reason')}:{})};
   preview=await services.planning.suggest(payload);const box=modal.querySelector('#plan-preview');box.innerHTML=`<h3>Plano: ${n(preview.plannedPieces)} peças</h3><p>${preview.intervals.map(i=>`${date(i.startedAt,true)}: ${n(i.plannedPieces)}`).join('<br>')}</p><label class="check-line"><input name="confirmed" type="checkbox" required>Conferi OP, família, pausas e quantidades. Aprovar plano.</label>`;
   modal.querySelectorAll('.form-grid input,.form-grid select').forEach(control=>control.disabled=true);modal.querySelector('[type=submit]').textContent='Aprovar plano';return {keepOpen:true};
  }});return;
 }
 if(command==='production'||command==='confirm'||command==='reconcile'){
  requireThat(operator(state),'FORBIDDEN');const header=state.period.intervalHeaders?.[id];requireThat(header,'NOT_FOUND');const chain=ledgerView(header);
  if(command==='confirm'||command==='reconcile'){const rows=(state.period.effective?.production??[]).filter(r=>r.intervalId===id&&r.basis==='gross'),sum=rows.reduce((n,r)=>n+r.quantity,0);showModal(command==='reconcile'?'Reconciliar confirmação':'Confirmar intervalo',`<p>${date(header.startedAt,true)} – ${date(header.endedAt,true)} · OP ${e(header.context.order)} · ${n(sum)} peças brutas registradas</p>${field('Total bruto confirmado (peças)','quantity',sum)}<label class="check-line"><input name="confirmed" type="checkbox" required>Confirmar todos os incrementos e correções deste intervalo</label>`,{footer:'Confirmar intervalo',submit:data=>services.plannedProduction[command==='reconcile'?'reconcile':'confirm'](id,{expectedRevision:chain.last?.id??null,confirmedGrossPieces:num(data,'quantity')})});return;}
  showModal('Apontar incremento',`<p>${date(header.startedAt,true)} – ${date(header.endedAt,true)} · OP ${e(header.context.order)} · lote ${e(header.context.lot)} · turno ${e(header.context.shift)}</p><div class="form-grid">${field('Quantidade (peças)','quantity')}<label class="field">Base<select name="basis"><option value="gross">Produção bruta</option><option value="good">Peças boas</option></select></label>${field('Início','startedAt',local(header.startedAt),'datetime-local')}${field('Fim','endedAt',local(header.endedAt),'datetime-local')}</div>`,{submit:async data=>{const record=await services.plannedProduction.record(id,{id:crypto.randomUUID(),quantity:num(data,'quantity'),basis:data.get('basis'),startedAt:saoPauloInstant(data.get('startedAt'),'startedAt'),endedAt:saoPauloInstant(data.get('endedAt'),'endedAt'),expectedRevision:chain.last?.id??null,origin:state.simulation?'demo':'manual'});if(record.eventDate>state.toDate)state.toDate=record.eventDate;return record;}});return;
 }
 if(command==='run'||command==='advance-run'){
  requireThat(operator(state),'FORBIDDEN');const run=state.period.runs?.filter(r=>r.runId===id).at(-1),next=run?['productionStartedAt','productionEndedAt','machineEndedAt'].find(k=>run[k]==null):'machineStartedAt';requireThat(next,'INVALID_TRANSITION');
  const label={machineStartedAt:'Máquina ligada',productionStartedAt:'Produção iniciada',productionEndedAt:'Produção encerrada',machineEndedAt:'Máquina desligada'}[next];
  showModal('Registrar horário · '+label,`<div class="form-grid"><p>OP ${e((run?.context??context).order)} · Lote ${e((run?.context??context).lot)} · Turno ${e((run?.context??context).shift)}</p>${field(label,'at',local(Date.now()),'datetime-local')}</div>`,{submit:data=>run?services.runs.advance(id,{expectedRevision:run.id,[next]:timestamp(data)}):services.runs.start({context,machineStartedAt:timestamp(data)})});return;
 }
 requireThat(false,'INVALID_KIND');
}
