import {aggregateOee,periodReliability,periodMicroStops} from '../domain/period-metrics.js';
import {calculateOee,calculateReliability,unionSeconds} from '../domain/oee.js';
import {productiveWindows,latestPlans,netSeconds} from '../domain/planning.js';
import {matchesScope} from '../domain/production-policy.js';
import {productivityView} from './nhpl.js';
import {escapeRecordText as e,number as n,date,dateWindow} from './format.js';
import {saoPauloInstant} from './forms.js';
import {stableStringify} from '../domain/canonical.js';
const btn=(label,action,icon='plus')=>`<button class="btn" data-action="${e(action)}"><i data-lucide="${icon}"></i>${e(label)}</button>`;
const pct=value=>value==null?'Indisponível':n(value*100,2)+'%';
export const oeeReasons={'history-incomplete':'Trecho sem observação; cobertura incompleta','planned-time-required':'Tempo planejado ausente','operating-time-required':'Classificar paradas / confirmar cobertura','ideal-cycle-required':'Ciclo ideal não definido','production-required':'Confirmar produção bruta','quality-required':'Confirmar boas de primeira passagem','no-production':'Sem produção confirmada para qualidade/desempenho','performance-inconsistent':'Desempenho > 100%: conferir ciclo, contagem e tempos','time-inconsistent':'Tempos incompatíveis','quality-inconsistent':'Boas excedem o total','reference-crosses-period':'A referência muda neste intervalo','inspection-outdated':'Inspeção anterior à revisão de produção'};
Object.assign(oeeReasons,{'reference-conflict':'Referências conflitantes; revisão técnica necessária','confirmation-outdated':'Reconciliar confirmação após a correção','plan-conflict':'Planos sobrepostos','revision-mismatch':'Revisão do plano divergente','correction-conflict':'Correções conflitantes','incomplete-query':'Consulta incompleta','no-period-allocation':'Intervalo sem detalhamento neste recorte','confirmation-mismatch':'Confirmação não corresponde aos registros','revision-pending':'Revisão de plano pendente','obsolete-plan':'Plano substituído; reconciliar dados'});
const recordingFields=c=>['order','lot','shift'].map((k,i)=>`<label class="field">${['OP','Lote','Turno'][i]}<input name="context_${k}" value="${e(c[k]??'')}" required maxlength="100"></label>`).join('');
const recordedContext=(data,context)=>({...context,...Object.fromEntries(['order','lot','shift'].map(k=>[k,String(data.get('context_'+k)??'').trim()]))});
const local=t=>new Date(t-10800000).toISOString().slice(0,19);
const input=(label,key,val='',type='text')=>`<label class="field">${e(label)}<input name="${key}" type="${type}" ${type==='datetime-local'?'step="1"':''} value="${e(val)}" required></label>`;
export function technicalView(state,{now=state.asOf??Date.now()}={}) {
 const technical=state.technical??[],segments=productivityView(state).segments,plans=latestPlans(state.period.plans??[]),allStops=state.period.effective?.stoppages??[];
 const evaluated=segments.filter(s=>s.intervalId&&s.from<now&&s.state!=='programmed').map(s=>{
  const through=Math.min(now,s.to),plan=plans.find(p=>p.id===s.planRevisionId),planned=plan?netSeconds(plan,s.from,through):null;
  const refs=technical.filter(r=>r.kind==='reference'&&matchesScope(r.context,s.context)).sort((a,b)=>a.effectiveFrom-b.effectiveFrom);
  const ref=refs.filter(r=>r.effectiveFrom<=s.from).at(-1),crosses=refs.some(r=>r.effectiveFrom>s.from&&r.effectiveFrom<through);
  const applicable=refs.filter(r=>r.effectiveFrom<s.to),refConflict=new Set(applicable.map(r=>r.supersedes??'root')).size!==applicable.length;
  const stops=allStops.filter(r=>matchesScope(s.context,r.context)&&r.startedAt<through&&(r.endedAt??through)>s.from);
  const classified=stops.map(stop=>({stop,classification:technical.filter(r=>r.kind==='classification'&&r.stopId===stop.id).at(-1)}));
  const live=state.client?.mode==='live',gap=(state.liveCoverage?.gaps??[]).some(g=>g.from<through&&g.to>s.from);
  const pending=state.period.coverage?.stoppages!==true||classified.some(x=>!x.classification||(!live&&x.stop.endedAt==null)||x.stop.revisionConflict||x.classification.stopFingerprint!==stableStringify([x.stop.startedAt,x.stop.endedAt??null,x.stop.correctionId??null])||x.classification.category==='outside-plan'&&plan&&productiveWindows(plan).some(w=>x.stop.startedAt<w.endedAt&&(x.stop.endedAt??through)>w.startedAt));
  const loss=plan?productiveWindows(plan).reduce((sum,w)=>sum+unionSeconds(classified.filter(x=>x.classification?.category==='availability').map(x=>x.stop),Math.max(s.from,w.startedAt),Math.min(through,w.endedAt)),0):null;
  const inspection=technical.filter(r=>r.kind==='inspection'&&r.intervalId===s.intervalId).at(-1);
  const rows=(state.period.effective?.production??[]).filter(r=>r.intervalId===s.intervalId);
  const trusted=inspection?.productionFingerprint===stableStringify(rows.map(r=>[r.id,r.quantity,r.correctionId??null]).sort((a,b)=>a[0].localeCompare(b[0])));
  const result=calculateOee({plannedSeconds:planned,runSeconds:pending?null:planned-loss,idealSeconds:crosses?null:ref?.idealSeconds,total:s.grossPieces,firstPassGood:trusted?inspection.firstPassGood:null,complete:s.state==='final'&&state.period.nhplComplete===true});
  if(inspection&&!trusted)result.reason='inspection-outdated';
  if(crosses)result.reason='reference-crosses-period';
  if(refConflict){result.performance=null;result.oee=null;result.reason='reference-conflict';result.state='unavailable';}
  if(gap){result.runSeconds=null;result.availability=null;result.performance=null;result.oee=null;result.reason='history-incomplete';result.state='unavailable';}
  if(s.reason&&!['policy-required','policy-conflict','confirmation-required','production-required','awaiting-update','future'].includes(s.reason)){result.performance=null;result.quality=null;result.oee=null;result.reason=s.reason;result.state='unavailable';}
  const crossingFailure=classified.some(x=>x.classification?.failure&&(x.stop.startedAt<s.from||(x.stop.endedAt??Infinity)>s.to));
  const rel=calculateReliability({operatingSeconds:result.runSeconds,repairs:classified.filter(x=>x.classification?.failure&&x.stop.startedAt>=s.from&&(x.stop.endedAt??Infinity)<=s.to).map(x=>x.classification),complete:inspection?.historyComplete===true&&!pending&&!crossingFailure&&s.state==='final'});
  const micros=stops.filter(r=>r.endedAt!=null&&!r.planned&&(r.endedAt-r.startedAt)/1000<=(ref?.microStopSeconds??60));
  return {...s,...result,referenceId:ref?.id,inspectionId:inspection?.id,classificationIds:classified.map(x=>x.classification?.id).filter(Boolean),reliability:rel,microCount:micros.length,microSeconds:unionSeconds(micros,s.from,s.to)};
 });
 const valid=evaluated.filter(s=>s.oee!=null),aggregate=aggregateOee(evaluated),windows=state.operationalQuery?.windows??[dateWindow(state.fromDate,state.toDate)],manualCoverage=evaluated.length>0&&evaluated.every(s=>technical.find(r=>r.id===s.inspectionId)?.historyComplete===true);
 if(aggregate.oee!=null&&state.period.coverage?.production===false)aggregate.state='partial';
 const reliability=periodReliability({plans,stops:allStops,classifications:technical.filter(r=>r.kind==='classification'),windows,now,coverage:{complete:state.period.nhplComplete===true&&state.period.coverage?.stoppages===true&&(state.client?.mode==='live'?state.liveCoverage?.complete===true:manualCoverage),provisional:state.client?.mode==='live'}}),micros=periodMicroStops({stops:allStops,references:technical.filter(r=>r.kind==='reference'),windows});
 return {segments:evaluated,aggregate,reliability,coverage:{evaluated:valid.length,total:evaluated.length},microCount:micros.count,microSeconds:micros.seconds};
}
export function technicalMarkup(state,{compact=false}={}) {
 const v=technicalView(state),a=v.aggregate,eng=['admin','engineer'].includes(state.actor?.role),op=['admin','engineer','operator'].includes(state.actor?.role);
 return `<section class="data-section"><div class="section-heading"><div><h2>OEE e confiabilidade</h2><p>${v.coverage.evaluated}/${v.coverage.total} intervalos com bases completas · ${a?.state==='final'?'Confirmado':'Parcial / pendente'}</p></div><div class="toolbar-right">${eng?btn('Referência de OEE','tech:reference','sliders-horizontal'):''}${btn('Memória CSV','tech:export','download')}</div></div><div class="metrics">${[['Disponibilidade',a?.availability],['Desempenho',a?.performance],['Qualidade',a?.quality],['OEE',a?.oee]].map(([title,value])=>`<article class="metric"><div class="metric-title">${title}</div><div class="metric-value">${pct(value)}</div></article>`).join('')}</div><div class="cep-indices"><div><span>Microparadas</span><strong>${n(v.microCount)}</strong></div><div><span>Duração acumulada</span><strong>${n(v.microSeconds)} s</strong></div></div>${compact?'':`<div class="table-wrap"><table class="data-table"><thead><tr><th>Intervalo / OP</th><th>Bases (s / peças)</th><th>A / P / Q / OEE</th><th>Confiabilidade</th><th>Situação / ação</th></tr></thead><tbody>${v.segments.map(s=>`<tr><td>${date(s.from,true)}<div class="small muted">${e(s.context.order)} · ${e(s.context.variant??'')}</div></td><td>Planejado ${n(s.plannedSeconds)} · operação ${n(s.runSeconds)}<div class="small muted">Ciclo ideal ${n(s.idealSeconds)} s/peça · total ${n(s.total)} · primeira passagem ${n(s.firstPassGood)}</div></td><td>${pct(s.availability)} / ${pct(s.performance)} / ${pct(s.quality)}<div><strong>${pct(s.oee)}</strong></div></td><td>MTBF ${n(s.reliability.mtbf==null?null:s.reliability.mtbf/60)} min<div class="small muted">MTTR ${n(s.reliability.mttr==null?null:s.reliability.mttr/60)} min · taxa ${n(s.reliability.failureRate)} falhas/h</div></td><td>${e(oeeReasons[s.reason]??(s.state==='final'?'Confirmado':'Parcial'))}${op?btn('Inspeção / cobertura','tech:inspect:'+s.intervalId,'check-check'):''}</td></tr>`).join('')||'<tr><td colspan="5">Sem intervalo produtivo neste contexto</td></tr>'}</tbody></table></div>`}<p class="source-notes">Produtividade de 95% é separada do OEE. Takt 12 s não é ciclo ideal. MTBF/MTTR exigem falhas e reparos classificados; ausência não equivale a zero.</p></section>`;
}
export function inspectionsMarkup(state){
 const v=technicalView(state),op=['admin','engineer','operator'].includes(state.actor?.role);
 return `<section class="data-section"><h2>Inspeção de primeira passagem</h2><p>Peças boas na primeira passagem sustentam a qualidade do OEE. A inspeção fica vinculada à revisão dos apontamentos.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Intervalo / OP</th><th>Brutas / boas de primeira passagem</th><th>Cobertura e ação</th></tr></thead><tbody>${v.segments.map(s=>`<tr><td>${date(s.from,true)} · ${e(s.context.order)}</td><td>${n(s.total)} / ${n(s.firstPassGood)}</td><td>${e(oeeReasons[s.reason]??(s.state==='final'?'Confirmado':'Em andamento'))}${op?btn('Inspeção / cobertura','tech:inspect:'+s.intervalId,'check-check'):''}</td></tr>`).join('')||'<tr><td colspan="3">Sem intervalo produtivo neste contexto.</td></tr>'}</tbody></table></div></section>`;
}
export function captureMarkup(state,{compact=false}={}) {
 const events=(state.technical??[]).filter(r=>r.kind==='event').sort((a,b)=>a.event.occurredAt-b.event.occurredAt),last=events.at(-1),source=last?.event;
 const stale=!source||Date.now()-source.occurredAt>30000,can=['admin','engineer','operator'].includes(state.actor?.role);
 if(compact)return `<section class="data-section"><h2>Estado da fonte</h2><strong>${source?.state==='disconnected'?'Comunicação perdida':stale?'Sem atualização recente':'Recebendo eventos'}</strong><p>${source?date(source.occurredAt,true)+' · '+e(source.sourceId):'Fonte não configurada'}</p>${last?.gap?'<p class="badge warn">Lacuna de sequência</p>':''}</section>`;
 return `<section class="data-section"><div class="section-heading"><h2>Fonte de dados · NHPL</h2><div class="toolbar-right">${can?btn('Importar eventos','tech:events','upload')+btn(state.connectorActive?'Pausar conector':'Conectar pasta local',state.connectorActive?'connector-stop':'tech:connector','plug-zap'):''}</div></div><div class="setting-row"><strong>${!source?'Aguardando fonte':source.state==='disconnected'?'Comunicação perdida':stale?'Dado sem atualização recente':'Recebendo eventos'}</strong><span>${source?date(source.occurredAt,true):'Nenhum evento recebido'}</span></div>${state.connectorMessage?`<p role="status">${e(state.connectorMessage)}</p>`:''}<p class="source-notes">Fonte ${e(source?.sourceId??'não configurada')} · sequência ${n(source?.sequence)}.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Recebido / origem</th><th>Tipo / sequência</th><th>Estado / valor</th><th>Diagnóstico</th></tr></thead><tbody>${events.slice(-15).reverse().map(r=>`<tr><td>${date(r.event.occurredAt,true)} · ${e(r.event.sourceId)}</td><td>${e(r.event.type)} / ${r.event.sequence}</td><td>${e(r.event.state??r.event.quantity??r.event.count??r.event.raw??'Boa validada')}</td><td>${r.gap?'Lacuna de sequência':'Recebimento registrado'}</td></tr>`).join('')||'<tr><td colspan="4">Sem eventos importados</td></tr>'}</tbody></table></div></section>`;
}
export function occurrencesMarkup(state) {
 const rows=(state.technical??[]).filter(r=>r.kind==='occurrence'&&matchesScope(state.context,r.context)),can=['admin','engineer','operator'].includes(state.actor?.role),eng=['admin','engineer'].includes(state.actor?.role);
 return `<section class="data-section"><div class="section-heading"><h2>Ocorrências</h2>${can?btn('Nova ocorrência','tech:occurrence','clipboard-pen'):''}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>Data / tipo</th><th>Relato</th><th>Situação</th><th>Ação</th></tr></thead><tbody>${rows.map(r=>{const decisions=(state.technical??[]).filter(x=>x.kind==='occurrence-decision'&&x.occurrenceId===r.id);return `<tr><td>${date(r.occurredAt,true)} · ${e(r.type)}</td><td>${e(r.note)}</td><td>${e(decisions.at(-1)?.decision??'Aguardando análise')}</td><td>${btn('Histórico','tech:occurrence-detail:'+r.id,'history')}${eng?btn('Tratar','tech:decide-occurrence:'+r.id,'check'):''}</td></tr>`;}).join('')||'<tr><td colspan="4">Sem ocorrências neste contexto</td></tr>'}</tbody></table></div></section>`;
}
export function stopsTechnicalMarkup(state){const rows=state.period.effective?.stoppages??[];return `<section class="data-section"><h2>Classificação técnica das paradas</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Parada</th><th>Classificação</th><th>Ação</th></tr></thead><tbody>${rows.map(s=>{const c=(state.technical??[]).filter(r=>r.kind==='classification'&&r.stopId===s.id).at(-1);return `<tr><td>${date(s.startedAt,true)} · ${s.endedAt==null?'Em aberto':n((s.endedAt-s.startedAt)/60000)+' min'}</td><td>${e(({availability:'Disponibilidade',performance:'Desempenho / microparada','outside-plan':'Fora do planejamento'})[c?.category]??'Pendente')}${c?.failure?' · Falha':''}</td><td>${['admin','engineer'].includes(state.actor?.role)?btn('Classificar','tech:classify:'+s.id,'sliders-horizontal'):'Aguardando equipe técnica'}</td></tr>`;}).join('')}</tbody></table></div></section>`;}
export function operatorToolbar(state){
 if(!['admin','engineer','operator'].includes(state.actor?.role))return '';
 const runs=new Map();for(const r of state.period.runs??[])if(matchesScope(state.context,r.context))runs.set(r.runId,r);
 const run=[...runs.values()].find(r=>r.machineEndedAt==null);
 const label=run?run.productionStartedAt==null?'Iniciar produção':run.productionEndedAt==null?'Encerrar produção':'Desligar máquina':'Ligar máquina';
 return `<div class="operation-toolbar">${btn(label,run?'nhpl:advance-run:'+run.runId:'nhpl:run','power')}${btn('Produção','form:production','package-plus')}${btn('Parâmetros','form:collection','sliders-horizontal')}${btn('Parada','form:stoppage','pause')}${btn('Refugo / perda','form:loss','circle-minus')}${btn('Ocorrência','tech:occurrence','clipboard-pen')}</div>`;
}
export async function technicalAction(command,{state,services,showModal,downloadCsv,refresh,toast,startConnector}) {
 const[,action,id]=command.split(':'),service=services.technical,context=structuredClone(state.context);
 if(action==='export'){const rows=technicalView(state).segments.map(s=>({...s,context:JSON.stringify(s.context),reliability:JSON.stringify(s.reliability),classificationIds:s.classificationIds.join('|'),origin:state.client.mode??'operational'}));downloadCsv(await services.csv.exportRecords(rows,[...new Set(rows.flatMap(r=>Object.keys(r)))]),'msa-oee-'+state.toDate+'.csv');return;}
 if(action==='occurrence-detail'){const row=(state.technical??[]).find(r=>r.id===id);const decisions=(state.technical??[]).filter(r=>r.occurrenceId===id);showModal('Histórico da ocorrência',`<p>${e(row.note)}</p>${decisions.map(r=>`<p>${date(r.createdAt,true)} · ${e(r.createdBy)} · ${e(r.decision)}: ${e(r.note)}</p>`).join('')}`);return;}
 if(action==='occurrence'||action==='decide-occurrence'){
  showModal(action==='occurrence'?'Registrar ocorrência':'Tratar ocorrência',`${action==='occurrence'?'<div class="form-grid">'+recordingFields(context)+'</div>':''}<label class="field">${action==='occurrence'?'Tipo':'Decisão'}<select name="type">${(action==='occurrence'?[['process','Processo'],['quality','Qualidade'],['maintenance','Manutenção'],['safety','Segurança']]:[['analyzing','Iniciar análise'],['resolved','Concluir'],['new-analysis','Solicitar nova análise']]).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label class="field">${action==='occurrence'?'Ocorrência':'Justificativa'}<textarea name="note" required maxlength="2000"></textarea></label>`,{submit:data=>action==='occurrence'?service.occurrence({context:recordedContext(data,context),type:data.get('type'),note:data.get('note'),occurredAt:Date.now()}):service.decideOccurrence(id,{decision:data.get('type'),note:data.get('note')})});return;
 }
 if(action==='reference'){
  const previous=(state.technical??[]).filter(r=>r.kind==='reference'&&matchesScope(r.context,context)).sort((a,b)=>a.effectiveFrom-b.effectiveFrom).at(-1);
  showModal('Referência técnica OEE',`<p>OP ${e(context.order)} · ${e(context.lot)} · turno ${e(context.shift)} · ${e(context.variant??'')}</p><div class="form-grid">${recordingFields(context)}${input('Ciclo ideal (s/peça)','idealSeconds',previous?.idealSeconds??'')}${input('Microparada máxima (s)','microStopSeconds',previous?.microStopSeconds??60)}${input('Vigência','effectiveFrom',local(Date.now()),'datetime-local')}${input('Fonte / revisão técnica','source',previous?.source??'')}</div><p class="source-notes">Takt não preenche este campo. A revisão não altera referências históricas.</p>`,{submit:data=>service.reference({context:recordedContext(data,context),idealSeconds:Number(String(data.get('idealSeconds')).replace(',','.')),microStopSeconds:Number(data.get('microStopSeconds')),effectiveFrom:saoPauloInstant(data.get('effectiveFrom')),source:data.get('source'),...(()=>{const c=recordedContext(data,context),p=(state.technical??[]).filter(r=>r.kind==='reference'&&stableStringify(r.context)===stableStringify(c)).sort((a,b)=>a.effectiveFrom-b.effectiveFrom).at(-1);return p?{supersedes:p.id}:{};})()})});return;
 }
 if(action==='inspect'){showModal('Confirmar inspeção e cobertura',`${input('Boas de primeira passagem (peças)','firstPassGood')}<label class="check-line"><input name="historyComplete" type="checkbox">Histórico de falhas e paradas completo neste intervalo</label>${input('Fonte / evidência da inspeção','note')}`,{submit:data=>service.inspect({intervalId:id,firstPassGood:Number(data.get('firstPassGood')),historyComplete:data.has('historyComplete'),note:data.get('note')})});return;}
 if(action==='classify'){
  const stop=(state.period.effective?.stoppages??[]).find(r=>r.id===id);
  showModal('Classificar parada',`<label class="field">Perda<select name="category"><option value="availability">Disponibilidade (inclui setup em tempo produtivo)</option><option value="performance">Desempenho / pequena parada</option><option value="outside-plan">Fora do tempo programado</option></select></label><label class="check-line"><input name="failure" type="checkbox">Falha do equipamento</label><div class="form-grid">${input('Início do reparo (se falha)','repairStartedAt',local(stop.startedAt),'datetime-local')}${input('Fim do reparo (se falha)','repairEndedAt',local(stop.endedAt??Date.now()),'datetime-local')}${input('Critério / justificativa','note')}</div>`,{submit:data=>service.classify({stopId:id,category:data.get('category'),failure:data.has('failure'),note:data.get('note'),...(data.has('failure')?{repairStartedAt:saoPauloInstant(data.get('repairStartedAt')),repairEndedAt:saoPauloInstant(data.get('repairEndedAt'))}:{})})});return;
 }
 if(action==='evidence'){showModal('Evidências de Qualidade',`<div class="form-grid">${[['Plano de controle / revisão','controlPlan'],['Inspeção','inspection'],['Resultado do ensaio','testResult'],['Performance do produto','performance'],['Justificativa','note']].map(([l,k])=>input(l,k)).join('')}</div>`,{submit:data=>service.evidence({...Object.fromEntries(['controlPlan','inspection','testResult','performance','note'].map(k=>[k,data.get(k)])),reviewId:id})});return;}
 if(action==='events'){
  showModal('Importar eventos JSON',`<label class="field">Arquivo<input id="event-file" type="file" accept=".json,application/json"></label><label class="field">Eventos<textarea name="events" rows="12" required placeholder="[ { schemaVersion: 1, ... } ]"></textarea></label><label class="check-line"><input name="confirmed" required type="checkbox">Conferi origem, contexto e horários</label><p class="source-notes">Eventos repetidos não duplicam registros. Conflitos interrompem o lote; os anteriores permanecem registrados.</p>`,{submit:async data=>{const events=JSON.parse(data.get('events'));if(!Array.isArray(events)||events.length>500)throw Object.assign(new Error(),{code:'EVENT_FORMAT'});let count=0;for(const event of events){await service.ingest(event);count++;}return {successMessage:count+' eventos conferidos.'};}});return;
 }
 if(action==='connector'){
  showModal('Conector local de arquivos',`<p>Loopback: 127.0.0.1:5188. Origem e pasta configuradas pelo responsável.</p><div id="connector-status"></div><label class="check-line"><input required name="confirmed" type="checkbox">Autorizar consumo desta fila local nesta sessão</label>`,{footer:'Receber fila',submit:async()=>{
   const res=await fetch('http://127.0.0.1:5188/events',{cache:'no-store'});if(!res.ok)throw new Error('Conector indisponível');const q=await res.json();if(!Array.isArray(q.events)||q.events.length>500)throw new Error('Fila inválida');
   for(const event of q.events)await service.ingest(event);startConnector?.();return {successMessage:q.events.length+' eventos reconciliados. Acompanhamento automático ativo.'};}});return;
 }
}
