import {visibleNavigation,initialRoute} from './access.js';
export const pagePurposes={dashboard:'Como está a produção neste período?',production:'Compare o realizado, confira o planejamento e registre a produção.',equipment:'Consulte o cadastro, a situação registrada e as últimas leituras.',parameters:'Confira as leituras do processo e registre uma nova coleta.',stoppages:'Acompanhe as paradas e os tempos de reparo.',quality:'Confira inspeções, refugos e perdas.',indicators:'Entenda os resultados e as bases de cada indicador.',engineering:'Revise análises, evidências e correções.',history:'Encontre registros, autoria, origem e revisões.',registry:'Mantenha os cadastros e seus vínculos.',settings:'Ajuste sua conta, aparência e verificações técnicas.',cep:'Estude a variação em contextos e versões compatíveis.'};
export function groupedNavigation(items,render){return [['Acompanhar',['dashboard','production','equipment','indicators']],['Operar',['parameters','stoppages','quality']],['Analisar',['engineering','cep','history']],['Gerenciar',['registry']]].map(([label,ids])=>{const visible=ids.map(id=>items.find(row=>row[0]===id)).filter(Boolean);return visible.length?`<div class="navigation-group"><span class="rail-group">${label}</span>${visible.map(render).join('')}</div>`:'';}).join('');}
export function resolveWorkspaceRoute({route,tab,role}){
 if(route==='planning')return {route:'production',tab:'planning'};
 if(route==='operations'){if(tab==='stoppages')return {route:'stoppages',tab:'history'};if(tab==='losses')return {route:'quality',tab:'losses'};return {route:'production',tab:tab==='hourly'?'summary':tab==='occurrences'?'occurrences':'records'};}
 if(['production','stoppages','quality'].includes(route))return {route,tab};
 if(!['settings','capture','tv'].includes(route)&&!visibleNavigation(role).includes(route)){const first=initialRoute(role);return resolveWorkspaceRoute({route:first,role});}return {route,tab};
}
export function pageTabs(route,selected,items){return `<div class="tabs task-tabs" role="tablist" aria-label="Áreas da página">${items.map(([id,label])=>`<button type="button" role="tab" aria-selected="${id===selected}" class="tab ${id===selected?'active':''}" data-page-tab="${id}" data-page-route="${route}">${label}</button>`).join('')}</div>`;}
