import {readFile,writeFile} from 'node:fs/promises';
const file=new URL('../firebase/database.rules.json',import.meta.url),document=JSON.parse(await readFile(file,'utf8')),ws=document.rules.workspaces.$ws;
const role="root.child('workspaces').child($ws).child('members').child(auth.uid).child('role').val()";
const hash={'.validate':"newData.isString() && newData.val().matches(/^[a-f0-9]{64}$/)"};
const id={'.validate':"newData.isString() && newData.val().matches(/^[A-Za-z0-9_-]{1,100}$/)"};
const date={'.validate':"newData.isString() && newData.val().matches(/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/)"};
const base="root.child('workspaces').child($ws)",selected=base+".child('productionCases').child(newData.child('recording').child('productionCaseId').val())";
const matching=['machineId','processId','productId','order','lot','shift','variant'].map(k=>["query","recording"].map(group=>selected+".child('"+k+"').val() == newData.child('"+group+"').child('context').child('"+k+"').val()").join(' && ')).join(' && ');
const selection=selected+".exists() && "+matching+" && "+selected+".child('recipeVersionId').val() == newData.child('recording').child('context').child('recipe').val() && "+selected+".child('recipeVersionId').val() == newData.child('query').child('context').child('recipe').val() && "+selected+".child('operationalDate').val() == newData.child('query').child('fromDate').val() && "+selected+".child('operationalDate').val() == newData.child('query').child('toDate').val() && "+selected+".child('shift').val() == newData.child('query').child('shift').val()";
ws.presentationManifests={'.read':`auth != null && (${['admin','engineer','operator','viewer'].map(r=>`${role} == '${r}'`).join(' || ')})`,'$id':{
 '.write':`auth != null && ${role} == 'admin' && !data.exists() && newData.exists()`,
 '.validate':"newData.hasChildren(['id','packageId','version','origin','fromOperationalDate','toOperationalDate','defaultSelection','entries','entryCount','entriesHash','previewHash','backupHash','state','createdBy','createdAt']) && newData.child('entries').child('0').exists() && newData.child('entries').child((newData.child('entryCount').val() - 1) + '').exists()",
 id:{'.validate':'newData.val() == $id'},packageId:id,baseManifestId:{'.validate':"newData.isString() && root.child('workspaces').child($ws).child('presentationManifests').child(newData.val()).child('state').val() == 'published' && root.child('workspaces').child($ws).child('presentationManifests').child(newData.val()).child('packageId').val() == newData.parent().child('packageId').val()"},version:id,
 origin:{'.validate':"newData.val() == 'demo'"},state:{'.validate':"newData.val() == 'published'"},fromOperationalDate:date,toOperationalDate:date,
 defaultSelection:{'.validate':"newData.hasChildren(['query','recording']) && "+selection,query:{'.validate':'newData.hasChildren()'},recording:{'.validate':"newData.hasChild('productionCaseId')"},'$other':{'.validate':false}},
 entries:{'.validate':'newData.hasChildren()','$index':{'.validate':"$index.matches(/^(0|[1-9][0-9]*)$/) && newData.child('index').val() < newData.parent().parent().child('entryCount').val() && ($index == '0' || newData.parent().child((newData.child('index').val() - 1) + '').exists()) && newData.hasChildren(['index','path','scope','hash']) && $index == newData.child('index').val() + '' && root.child('workspaces').child($ws).child(newData.child('path').val()).exists()",index:{'.validate':'newData.isNumber() && newData.val() >= 0 && newData.val() % 1 == 0'},path:{'.validate':"newData.isString() && newData.val().matches(/^(machines|processes|products|pilots|parameters|parameterVersions|reasons|targets|targetRevisions|recipeVersions|productionCases|productionPolicies|productionPlans|productionIntervals|collections|production|losses|stoppages|machineRuns|reviews|technicalRecords|coverageWitnesses|corrections|plannedCorrections)(\\/[A-Za-z0-9_-]+)+$/)"},scope:{'.validate':"newData.val() == 'record' || (newData.val() == 'ledger-header' && newData.parent().child('path').val().matches(/^(productionPlans|productionIntervals|machineRuns|productionPolicies|targetRevisions)\\/[A-Za-z0-9_-]+$/) && root.child('workspaces').child($ws).child(newData.parent().child('path').val()).hasChild('firstSlotId'))"},hash,'$other':{'.validate':false}}},
 entryCount:{'.validate':'newData.isNumber() && newData.val() >= 1 && newData.val() <= 10000 && newData.val() % 1 == 0'},entriesHash:hash,previewHash:hash,backupHash:hash,
 createdBy:{'.validate':'newData.val() == auth.uid'},createdAt:{'.validate':'newData.val() == now'},'$other':{'.validate':false}
}};
await writeFile(file,JSON.stringify(document,null,2)+'\n');
