import test from 'node:test';
import assert from 'node:assert/strict';
import {assertFails} from '@firebase/rules-unit-testing';
import {setup,sdk} from '../helpers/firebase-env.js';
import {createFirebaseRepository} from '../../app/src/repositories/firebase-repository.js';
import {createMsaServices} from '../../app/src/services/create-msa.js';
test('NHPL service flow and direct SDK restrictions protect immutable chains and roles',async t=>{
 const env=await setup(t),db=uid=>env.authenticatedContext(uid).database(),path='workspaces/demo/';
 const service=(uid,role)=>createMsaServices({repo:createFirebaseRepository({db:db(uid),sdk,workspaceId:'demo'}),actor:{uid,role}});
 const adm=service('admin','admin'),eng=service('eng','engineer'),op=service('op','operator');
 await adm.nhpl.install({});const context={machineId:'nhpl',processId:'nhpl-montagem',productId:'nhpl-vgard-hp',order:'OP',lot:'L',shift:'1'},from=Date.now()-7200000,to=from+3600000;
 const policy=await eng.policies.create({id:'p',metric:'productivityPercent',value:95,effectiveFrom:from,source:'Fabiana',context:{machineId:'nhpl',processId:'nhpl-montagem'}});
 const plan=await eng.planning.approve({context,startedAt:from,endedAt:to,intervalMinutes:60,quantitySource:'informed',plannedPieces:300});
 const interval=plan.intervals[0],row=await op.plannedProduction.record(interval.id,{quantity:285,basis:'gross',startedAt:from,endedAt:to});
 await assertFails(sdk.set(sdk.ref(db('op'),path+'productionPlans/nhpl/createdBy'),'op'));
 await assertFails(sdk.set(sdk.ref(db('eng'),path+'productionPolicies/p/events/'+policy.id+'/value'),80));
 await assertFails(sdk.remove(sdk.ref(db('admin'),path+'productionPlans/nhpl')));
 await assertFails(sdk.set(sdk.ref(db('view'),path+'productionIntervals/'+interval.id+'/events/forged'),{id:'forged'}));
 await assertFails(sdk.set(sdk.ref(db('op'),path+'productionIntervals/'+interval.id+'/events/'+row.id+'/quantity'),999));
 const header=(await sdk.get(sdk.ref(db('op'),path+'productionIntervals/'+interval.id))).val(),event=header.events[row.id];
 await assertFails(sdk.set(sdk.ref(db('op'),path+'productionIntervals/'+interval.id+'/events/branch'),{...event,id:'branch',sequence:2,previousEventId:row.id}));
 await op.plannedProduction.confirm(interval.id,{expectedRevision:row.id,confirmedGrossPieces:285});
 const query={context,fromDate:new Date(from-10800000).toISOString().slice(0,10),toDate:new Date(to-10800000).toISOString().slice(0,10)};
 const result=await eng.getProductivity(query,{from,to});assert.equal(result.segments[0].percent,95);
 const correction=await op.plannedProduction.requestCorrection({recordType:'production',recordId:row.id,intervalId:interval.id,replacement:{...row,quantity:284},reason:'Conferência'});
 await assertFails(sdk.update(sdk.ref(db('op'),path+'plannedCorrections/'+correction.id),{state:'approved',decision:{state:'approved',by:'op',at:sdk.serverTimestamp(),justification:'Própria'}}));
 await eng.plannedProduction.decideCorrection(correction.id,{decision:'approved',justification:'Conferido'});
 const revised=await eng.getProductivity(query,{from,to});assert.equal(revised.segments[0].evaluation,'below');
 const closed=(await sdk.get(sdk.ref(db('op'),path+'productionIntervals/'+interval.id))).val(),closure=Object.values(closed.events).find(e=>e.kind==='closure');
 const reconciliation=await op.plannedProduction.reconcile(interval.id,{expectedRevision:closure.id,confirmedGrossPieces:284});assert.ok(reconciliation.correctionIds.includes(correction.id));
 const second=await eng.planning.approve({context,startedAt:from-7200000,endedAt:from-3600000,intervalMinutes:60,quantitySource:'informed',plannedPieces:300});
 await eng.planning.revise(second.planId,{machineId:'nhpl',reason:'Ajuste',plannedPieces:290});
 const retired=(await sdk.get(sdk.ref(db('op'),path+'productionIntervals/'+second.intervals[0].id))).val(),retirement=Object.values(retired.events).at(-1);
 await assertFails(sdk.set(sdk.ref(db('op'),path+'productionIntervals/'+second.intervals[0].id+'/events/'+retirement.nextSlotId),{id:retirement.nextSlotId,kind:'production',sequence:retirement.sequence+1,previousEventId:retirement.id,nextSlotId:'forged-next',quantity:1,basis:'gross',startedAt:from-7200000,endedAt:from-3600000,origin:'manual',createdBy:'op',createdAt:sdk.serverTimestamp()}));
});
